site_name: EVE Online Third-Party Developer Documentation
extra_javascript:
- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
- mdx_math
pages:
- Home: 'index.md'
- Guidelines and References:
    - 'Developer License': 'reference/license.md'
    - 'Guidelines': 'reference/guidelines.md'
    - 'Quick Reference': 'reference/reference.md'
- Formulas:
    - 'Warp-in Points': 'formulas/warpinpoints.md'
- Single Sign-On (SS0):
    - 'Introduction': 'sso/intro.md'
    - 'Authentication Flow': 'sso/authentication.md'
    - 'Refresh Tokens': 'sso/refreshtokens.md'
    - 'SSO For Browser Apps': 'sso/implicitflow.md'
    - 'Non-Browser Apps': 'sso/nonbrowserapps.md'
    - 'Obtain Character ID': 'sso/obtaincharacterid.md'
- CREST:
    - 'Introduction': 'crest/intro.md'
    - 'Authentication and Scopes': 'crest/authentication.md'
    - 'Versioning': 'crest/versioning.md'
    - 'Char - Contacts': 'crest/char_contacts.md'
    - 'Char - Fittings': 'crest/char_fittings.md'
    - 'Char - Waypoints': 'crest/char_waypoints.md'
    - 'Char - Location': 'crest/char_location.md'
    - 'Map - Constellations': 'crest/map_constellations.md'
    - 'Map - Planets': 'crest/map_planets.md'
    - 'Map - Regions': 'crest/map_regions.md'
    - 'Map - SolarSystems': 'crest/map_solarsystems.md'
    - 'Eve - Alliances': 'crest/eve_alliances.md'
    - 'Eve - Types': 'crest/eve_types.md'
    - 'Eve - DogmaAttributes': 'crest/eve_dogmaAttributes.md'
    - 'Eve - DogmaEffects': 'crest/eve_dogmaEffects.md'
    - 'Eve - Wars': 'crest/eve_wars.md'
- XML API:
    - 'Introduction': 'xmlapi/intro.md'
    - 'Authentication': 'xmlapi/authentication.md'
    - 'Caching': 'xmlapi/caching.md'
    - 'Endpoints Overview': 'xmlapi/endpoints.md'
    - 'Account - AccountStatus': 'xmlapi/account_accountstatus.md'
    - 'Account - APIKeyInfo': 'xmlapi/account_apikeyinfo.md'
    - 'Account - Characters': 'xmlapi/account_characters.md'
    - 'CallList': 'xmlapi/api_calllist.md'
    - 'Char - AccountBalance': 'xmlapi/char_accountbalance.md'
    - 'Char - AssetList': 'xmlapi/char_assetlist.md'
    - 'Char - Blueprints': 'xmlapi/char_blueprints.md'
    - 'Char - Bookmarks': 'xmlapi/char_bookmarks.md'
    - 'Char - CalendarEventAttendees': 'xmlapi/char_calendareventattendees.md'
    - 'Char - CharacterSheet': 'xmlapi/char_charactersheet.md'
    - 'Char - ChatChannels': 'xmlapi/char_chatchannels.md'
    - 'Char - ContactList': 'xmlapi/char_contactlist.md'
    - 'Char - ContractBids': 'xmlapi/char_contractbids.md'
    - 'Char - ContractItems': 'xmlapi/char_contractitems.md'
    - 'Char - Contracts': 'xmlapi/char_contracts.md'
    - 'Char - FacWarStats': 'xmlapi/char_facwarstats.md'
    - 'Char - IndustryJobs': 'xmlapi/char_industryjobs.md'
    - 'Char - IndustryJobsHistory': 'xmlapi/char_industryjobshistory.md'
    - 'Char - MailBodies': 'xmlapi/char_mailbodies.md'
    - 'Char - MailingLists': 'xmlapi/char_mailinglists.md'
    - 'Char - MailMessages': 'xmlapi/char_mailmessages.md'
    - 'Char - MarketOrders': 'xmlapi/char_marketorders.md'
    - 'Char - Notifications': 'xmlapi/char_notifications.md'
    - 'Char - NotificationTexts': 'xmlapi/char_notificationtexts.md'
    - 'Char - PlanetaryColonies': 'xmlapi/char_planetarycolonies.md'
    - 'Char - PlanetaryLinks': 'xmlapi/char_planetarylinks.md'
    - 'Char - PlanetaryPins': 'xmlapi/char_planetarypins.md'
    - 'Char - PlanetaryRoutes': 'xmlapi/char_planetaryroutes.md'
    - 'Char - Research': 'xmlapi/char_research.md'
    - 'Char - SkillInTraining': 'xmlapi/char_skillintraining.md'
    - 'Char - SkillQueue': 'xmlapi/char_skillqueue.md'
    - 'Char - Standings': 'xmlapi/char_standings.md'
    - 'Char - UpcomingCalendarEvents': 'xmlapi/char_upcomingcalendarevents.md'
    - 'Char - WalletJournal': 'xmlapi/char_walletjournal.md'
    - 'Char - WalletTransactions': 'xmlapi/char_wallettransactions.md'
    - 'Corp - AccountBalance': 'xmlapi/corp_accountbalance.md'
    - 'Corp - Bookmarks': 'xmlapi/corp_bookmarks.md'
    - 'Corp - CorporationSheet': 'xmlapi/corp_corporationsheet.md'
    - 'Corp - IndustryJobs': 'xmlapi/corp_industryjobs.md'
    - 'Corp - IndustryJobsHistory': 'xmlapi/corp_industryjobshistory.md'
    - 'Corp - MemberTracking': 'xmlapi/corp_membertracking.md'
    - 'Corp - StarbaseList': 'xmlapi/corp_starbaselist.md'
    - 'Corp - StarbaseDetail': 'xmlapi/corp_starbasedetail.md'
    - 'Corp - WalletJournal': 'xmlapi/corp_walletjournal.md'
    - 'Corp - WalletTransactions': 'xmlapi/corp_wallettransactions.md'
    - 'Constants': 'xmlapi/enumerations.md'
    - 'Eve - AllianceList': 'xmlapi/eve_alliancelist.md'
    - 'Eve - CharacterAffiliation': 'xmlapi/eve_characteraffiliation.md'
    - 'Eve - CharacterID': 'xmlapi/eve_characterid.md'
    - 'Eve - CharacterInfo': 'xmlapi/eve_characterinfo.md'
    - 'Eve - CharacterName': 'xmlapi/eve_charactername.md'
    - 'Eve - ConquerableStationList': 'xmlapi/eve_conquerablestationlist.md'
    - 'Eve - ErrorList': 'xmlapi/eve_errorlist.md'
    - 'Eve - RefTypes': 'xmlapi/eve_reftypes.md'
    - 'Eve - TypeName': 'xmlapi/eve_typename.md'
    - 'Map - FacWarSystems': 'xmlapi/map_facwarsystems.md'
    - 'Map - Jumps': 'xmlapi/map_jumps.md'
    - 'Map - Kills': 'xmlapi/map_kills.md'
    - 'Map - Sovereignty': 'xmlapi/map_sovereignty.md'
    - 'Server - ServerStatus': 'xmlapi/serv_serversstatus.md'
- Static Data Export:
    - 'Introduction': 'sde/intro.md'
    - 'Whats Included': 'sde/included.md'
    - 'Microsoft SQLServer Tables': 'sde/mssql.md'
    - 'SQLite Tables': 'sde/sqlite.md'
    - 'YAML Files': 'sde/yaml.md'
    - 'NPC Corporations Table (MSSQL)': 'sde/mssql_crpNPCCorporations.md'
    - 'EVE Units Table (MSSQL)': 'sde/mssql_eveUnits.md'
    - 'Inventory Flags Table (MSSQL)': 'sde/mssql_invFlags.md'
    - 'Inventory Items Table (MSSQL)': 'sde/mssql_invItems.md'
    - 'Inventory Name Table (MSSQL)': 'sde/mssql_invNames.md'
    - 'Stations Table (MSSQL)': 'sde/mssql_staStations.md'
    - 'Inventory Types File (YAML)': 'sde/yaml_typeIDs.md'
    - 'Conversions': 'sde/conversions.md'
    - 'Tips': 'sde/tips.md'
- Dogma:
    - 'Overview': 'dogma/overview.md'
- Image Server:
    - 'Introduction': 'imageserver/intro.md'
    - 'Image Export Collection': 'imageserver/iec.md'
- Image Server Test: 'imageserver.md'
theme: readthedocs